ALTER TABLE warera_battles
  ADD COLUMN war_id VARCHAR(64) NULL AFTER battle_id,
  ADD COLUMN region_id VARCHAR(64) NULL AFTER war_id,
  ADD COLUMN winner_country_id VARCHAR(64) NULL AFTER defender_country_id,
  ADD COLUMN attacker_score DECIMAL(18,2) NULL AFTER winner_country_id,
  ADD COLUMN defender_score DECIMAL(18,2) NULL AFTER attacker_score,
  ADD COLUMN attacker_damage BIGINT NULL AFTER defender_score,
  ADD COLUMN defender_damage BIGINT NULL AFTER attacker_damage,
  ADD COLUMN current_round_json JSON NULL AFTER defender_damage,
  ADD COLUMN rounds_json JSON NULL AFTER current_round_json,
  ADD COLUMN rounds_history_json JSON NULL AFTER rounds_json,
  ADD COLUMN battle_type VARCHAR(64) NULL AFTER rounds_history_json,
  ADD COLUMN total_rounds INT NULL AFTER battle_type,
  ADD COLUMN rounds_to_win INT NULL AFTER total_rounds,
  ADD COLUMN details_json JSON NULL AFTER raw_json,
  ADD COLUMN details_synced_at DATETIME(3) NULL AFTER details_json;

ALTER TABLE warera_users
  ADD COLUMN mu_id VARCHAR(64) NULL AFTER country_id,
  ADD COLUMN is_active TINYINT(1) NULL AFTER mu_id,
  ADD COLUMN military_rank INT NULL AFTER is_active,
  ADD COLUMN game_created_at DATETIME(3) NULL AFTER military_rank,
  ADD COLUMN game_updated_at DATETIME(3) NULL AFTER game_created_at,
  ADD COLUMN level INT NULL AFTER game_updated_at,
  ADD COLUMN total_xp BIGINT NULL AFTER level,
  ADD COLUMN total_damages BIGINT NULL AFTER total_xp,
  ADD COLUMN weekly_damage BIGINT NULL AFTER total_damages,
  ADD COLUMN total_damage_rank INT NULL AFTER weekly_damage,
  ADD COLUMN weekly_damage_rank INT NULL AFTER total_damage_rank,
  ADD COLUMN dates_json JSON NULL AFTER raw_json,
  ADD COLUMN stats_json JSON NULL AFTER dates_json,
  ADD COLUMN rankings_json JSON NULL AFTER stats_json,
  ADD COLUMN skills_json JSON NULL AFTER rankings_json,
  ADD COLUMN infos_json JSON NULL AFTER skills_json,
  ADD COLUMN full_profile_json JSON NULL AFTER infos_json,
  ADD COLUMN full_synced_at DATETIME(3) NULL AFTER full_profile_json;
